### ISSUE TITLE
Rendere il profile README friendly agli altri corsi

### ISSUE THREAD

**Issue by VaiTon** [csunibo/.github#7]
Attualmente per come è strutturato il README sono presenti solo i corsi di informatica. 

Anche aggiungendo tutti gli altri in successione il file diventerebbe illegibile. 

Propongo di creare un file per ogni corso e rendere il readme solo un introduzione al progetto, inserendo i vari link per i vari corsi.

I tools, essendo pochi, possono rimanere tranquillamente anche nel README principale.

Ho inoltre creato https://csunibo.github.io/dynamik/build per visualizzare i build status di tutti i progetti visualizzati da Dynamik.

**Comment by lucat1** [comment]
Approvo, è molto meglio a lungo termine. @foxyseta puoi pensarci tu al phrasing?

**Comment by foxyseta** [comment]
Un file per ogni corso nella stessa repo? Forse a questo punto potremmo linkare direttamente alle rispettive pagine dei CdL su Dynamik se esistono, o se nom esistono alla home di Dynamik

**Comment by lucat1** [comment]
Per me ci sta linkare a dynamik.
Complementerei la cosa con un link alla repo di github in ogni pagina di dynamik per chi vuole contribuire.

**Comment by foxyseta** [comment]
Ah sì assolutamente. Quindi lasceremo sia un pulsante "apri su github" sia il meccanismo drag and drop?

**Comment by lucat1** [comment]
Direi di sì

**Comment by foxyseta** [comment]
Molto bene. Non ho dimenticato questa issue. Sono solo molto indaffarato.

**Comment by foxyseta** [comment]
Chiudo con c263953
